# Generated by Django 4.1 on 2024-03-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_validated",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user has validated his account",
                verbose_name="validated",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="validation_code",
            field=models.CharField(
                default="",
                help_text="Code for validation",
                max_length=100,
                verbose_name="validation code",
            ),
        ),
    ]
