# Generated by Django 4.1 on 2024-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0003_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("employer", "employer"),
                    ("employee", "employee"),
                    ("moderator", "moderator"),
                ],
                default="",
                help_text="End user role",
                max_length=50,
                verbose_name="end user role",
            ),
        ),
    ]
