# Generated by Django 4.1 on 2024-03-17 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "Tag already exists!"},
                        help_text="News tag name",
                        max_length=30,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "newstag",
                "verbose_name_plural": "newstags",
            },
        ),
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        error_messages={}, help_text="Title", max_length=60
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        error_messages={}, help_text="Body", max_length=200
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("MD", "Markdown"),
                            ("HT", "HTML"),
                            ("TX", "Plain text"),
                        ],
                        max_length=2,
                    ),
                ),
                ("content", models.TextField(help_text="Content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        help_text="Tag list",
                        related_name="posts",
                        to="recrutingapp.newstag",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="Creator (author)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "newspost",
                "verbose_name_plural": "newsposts",
            },
        ),
    ]
