# Generated by Django 4.1 on 2024-04-03 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recrutingapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="City name", max_length=100)),
                ("region", models.CharField(help_text="Region name", max_length=100)),
            ],
            options={
                "verbose_name": "city",
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="EmployeeEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Institution"
                    ),
                ),
                ("content", models.TextField(help_text="Content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateto", models.DateField(blank=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "company",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Company"
                    ),
                ),
                ("content", models.TextField(help_text="Content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Gender", max_length=25)),
            ],
            options={
                "verbose_name": "skill",
                "verbose_name_plural": "skills",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Skill name", max_length=100)),
            ],
            options={
                "verbose_name": "skill",
                "verbose_name_plural": "skills",
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        error_messages={
                            "unique": "An employee with that email address already exists."
                        },
                        max_length=256,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.city",
                    ),
                ),
                (
                    "education",
                    models.ManyToManyField(
                        help_text="Education",
                        related_name="education",
                        to="recrutingapp.employeeeducation",
                    ),
                ),
                (
                    "experience",
                    models.ManyToManyField(
                        help_text="Experience",
                        related_name="experience",
                        to="recrutingapp.employeeexperience",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.gender",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        help_text="Skills",
                        related_name="skills",
                        to="recrutingapp.skill",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ee_profile",
                "verbose_name_plural": "ee_profiles",
            },
        ),
    ]
