# Generated by Django 4.1 on 2024-06-22 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("recrutingapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "Region already exists!"},
                        help_text="City name",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "city",
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_info",
                    models.CharField(
                        default="", help_text="Status info", max_length=150
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        error_messages={}, help_text="Title", max_length=60
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="Position")),
                ("salary", models.DecimalField(decimal_places=0, max_digits=10)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "cv",
                "verbose_name_plural": "cvs",
            },
        ),
        migrations.CreateModel(
            name="DocumentStatus",
            fields=[
                (
                    "id",
                    models.CharField(
                        choices=[
                            ("d", "Draft"),
                            ("p", "Pending"),
                            ("a", "Approved"),
                            ("r", "Rejected"),
                        ],
                        help_text="Status code",
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Status name", max_length=25)),
            ],
            options={
                "verbose_name": "status",
                "verbose_name_plural": "statuses",
            },
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_info",
                    models.CharField(
                        default="", help_text="Status info", max_length=150
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("established", models.DateField()),
                (
                    "email",
                    models.CharField(
                        error_messages={
                            "unique": "An employer with that email address already exists."
                        },
                        max_length=256,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                ("description", models.CharField(default="", max_length=250)),
                ("welcome_letter", models.TextField(default="", max_length=1000)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.city",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        help_text="Owner",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        choices=[
                            ("d", "Draft"),
                            ("p", "Pending"),
                            ("a", "Approved"),
                            ("r", "Rejected"),
                        ],
                        default="d",
                        help_text="Status",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.documentstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="Updated by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "employer",
                "verbose_name_plural": "employers",
            },
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Gender id",
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Gender name", max_length=25)),
            ],
            options={
                "verbose_name": "gender",
                "verbose_name_plural": "genders",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "Region already exists!"},
                        help_text="Region name",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "region",
                "verbose_name_plural": "regions",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={"unique": "Skill already exists!"},
                        help_text="Skill name",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "skill",
                "verbose_name_plural": "skills",
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_info",
                    models.CharField(
                        default="", help_text="Status info", max_length=150
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        error_messages={}, help_text="Title", max_length=60
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="Position")),
                ("salary", models.DecimalField(decimal_places=0, max_digits=10)),
                ("description", models.TextField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.city",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="recrutingapp.employer",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Owner",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        choices=[
                            ("d", "Draft"),
                            ("p", "Pending"),
                            ("a", "Approved"),
                            ("r", "Rejected"),
                        ],
                        default="d",
                        help_text="Status",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.documentstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="Updated by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vacancy",
                "verbose_name_plural": "vacancies",
            },
        ),
        migrations.AlterField(
            model_name="newspost",
            name="updated_by",
            field=models.ForeignKey(
                help_text="Updated by",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="VacancyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_info",
                    models.CharField(
                        default="", help_text="Status info", max_length=150
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutingapp.cv",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Owner",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        choices=[
                            ("d", "Draft"),
                            ("p", "Pending"),
                            ("a", "Approved"),
                            ("r", "Rejected"),
                        ],
                        default="d",
                        help_text="Status",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.documentstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="Updated by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutingapp.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "vacancy_response",
                "verbose_name_plural": "vacancy_responses",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "favorite",
                "verbose_name_plural": "favorites",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("birthday", models.DateField()),
                (
                    "email",
                    models.CharField(
                        error_messages={
                            "unique": "An employee with that email address already exists."
                        },
                        max_length=256,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                ("description", models.CharField(default="", max_length=250)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.city",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.gender",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        help_text="Owner",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        help_text="Skills",
                        related_name="skills",
                        to="recrutingapp.skill",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="Updated by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
            },
        ),
        migrations.CreateModel(
            name="DocumentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(help_text="Content", max_length=1024)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages",
            },
        ),
        migrations.CreateModel(
            name="CVResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_info",
                    models.CharField(
                        default="", help_text="Status info", max_length=150
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutingapp.cv",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Owner",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        choices=[
                            ("d", "Draft"),
                            ("p", "Pending"),
                            ("a", "Approved"),
                            ("r", "Rejected"),
                        ],
                        default="d",
                        help_text="Status",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.documentstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="Updated by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutingapp.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "cv_response",
                "verbose_name_plural": "cv_responses",
            },
        ),
        migrations.CreateModel(
            name="CVExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datefrom", models.DateField()),
                ("dateto", models.DateField(blank=True)),
                ("is_current", models.BooleanField(default=False)),
                ("company", models.CharField(max_length=100, verbose_name="Company")),
                ("position", models.CharField(max_length=100, verbose_name="Position")),
                ("content", models.TextField(help_text="Content")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.city",
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience",
                        to="recrutingapp.cv",
                    ),
                ),
            ],
            options={
                "verbose_name": "experience",
                "verbose_name_plural": "experience",
            },
        ),
        migrations.CreateModel(
            name="CVEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "institution",
                    models.CharField(max_length=100, verbose_name="Institution"),
                ),
                (
                    "specialty",
                    models.CharField(max_length=100, verbose_name="Speciality"),
                ),
                ("content", models.TextField(help_text="Content", max_length=1024)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="recrutingapp.cv",
                    ),
                ),
            ],
            options={
                "verbose_name": "education",
                "verbose_name_plural": "education",
            },
        ),
        migrations.AddField(
            model_name="cv",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recrutingapp.employee"
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="owner",
            field=models.ForeignKey(
                help_text="Owner",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="status",
            field=models.ForeignKey(
                choices=[
                    ("d", "Draft"),
                    ("p", "Pending"),
                    ("a", "Approved"),
                    ("r", "Rejected"),
                ],
                default="d",
                help_text="Status",
                on_delete=django.db.models.deletion.PROTECT,
                to="recrutingapp.documentstatus",
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="updated_by",
            field=models.ForeignKey(
                help_text="Updated by",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                help_text="Region",
                on_delete=django.db.models.deletion.PROTECT,
                to="recrutingapp.region",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancyresponse",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "cv"), name="unique_vacancy_cv"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "object_id", "content_type"),
                name="unique_user_content_type_object_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="cvresponse",
            constraint=models.UniqueConstraint(
                fields=("cv", "vacancy"), name="unique_cv_vacancy"
            ),
        ),
    ]
