# Generated by Django 4.1 on 2024-04-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recrutingapp", "0002_city_cv_documentstatus_gender_region_skill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recrutingapp.employee"
            ),
        ),
        migrations.AlterField(
            model_name="cveducation",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="recrutingapp.cv",
            ),
        ),
        migrations.AlterField(
            model_name="cvexperience",
            name="cv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experience",
                to="recrutingapp.cv",
            ),
        ),
    ]
