# Generated by Django 4.1 on 2024-04-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recrutingapp", "0003_alter_cv_employee_alter_cveducation_cv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="status",
            field=models.ForeignKey(
                choices=[
                    ("d", "Draft"),
                    ("p", "Pending"),
                    ("a", "Approved"),
                    ("r", "Rejected"),
                ],
                default="d",
                help_text="Status",
                on_delete=django.db.models.deletion.PROTECT,
                to="recrutingapp.documentstatus",
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="status_info",
            field=models.CharField(default="", help_text="Status info", max_length=150),
        ),
    ]
