# Generated by Django 4.1 on 2024-04-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recrutingapp", "0004_region_alter_city_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                error_messages={"unique": "Region already exists!"},
                help_text="City name",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(
                error_messages={"unique": "Region already exists!"},
                help_text="Region name",
                max_length=100,
                unique=True,
            ),
        ),
    ]
