# Generated by Django 4.1 on 2024-04-23 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recrutingapp", "0004_cv_status_cv_status_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="birthday",
            field=models.DateField(default=datetime.date(2024, 4, 23)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="Name"),
            preserve_default=False,
        ),
    ]
