# Generated by Django 4.1 on 2024-04-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recrutingapp", "0005_employee_birthday_employee_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="description",
            field=models.CharField(default="", max_length=250),
        ),
    ]
