# Generated by Django 4.1 on 2024-05-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recrutingapp", "0006_employee_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="cveducation",
            name="specialty",
            field=models.CharField(
                default="", max_length=100, verbose_name="Speciality"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cvexperience",
            name="position",
            field=models.CharField(
                default=" ", max_length=100, verbose_name="Position"
            ),
            preserve_default=False,
        ),
    ]
