# Generated by Django 4.1 on 2024-05-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recrutingapp", "0009_favorite_favorite_unique_user_content_type_object_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("established", models.DateField()),
                (
                    "email",
                    models.CharField(
                        error_messages={
                            "unique": "An employer with that email address already exists."
                        },
                        max_length=256,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                ("description", models.CharField(default="", max_length=250)),
                ("welcome_letter", models.TextField(default="", max_length=1000)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.city",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Owner",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="Updated by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "employer",
                "verbose_name_plural": "employers",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="owner",
            field=models.ForeignKey(
                help_text="Owner",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_info",
                    models.CharField(
                        default="", help_text="Status info", max_length=150
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        error_messages={}, help_text="Title", max_length=60
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="Position")),
                ("salary", models.DecimalField(decimal_places=0, max_digits=10)),
                ("description", models.TextField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.city",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recrutingapp.employer",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Owner",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        choices=[
                            ("d", "Draft"),
                            ("p", "Pending"),
                            ("a", "Approved"),
                            ("r", "Rejected"),
                        ],
                        default="d",
                        help_text="Status",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recrutingapp.documentstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="Updated by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vacancy",
                "verbose_name_plural": "vacancies",
            },
        ),
    ]
