# Generated by Django 4.1 on 2024-05-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recrutingapp", "0011_rename_employee_vacancy_employer"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="status",
            field=models.ForeignKey(
                choices=[
                    ("d", "Draft"),
                    ("p", "Pending"),
                    ("a", "Approved"),
                    ("r", "Rejected"),
                ],
                default="d",
                help_text="Status",
                on_delete=django.db.models.deletion.PROTECT,
                to="recrutingapp.documentstatus",
            ),
        ),
        migrations.AddField(
            model_name="employer",
            name="status_info",
            field=models.CharField(default="", help_text="Status info", max_length=150),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="recrutingapp.employer",
            ),
        ),
    ]
